(load "/root/quicklisp/setup.lisp")
(require :asdf)
(require :woo)
(require :postmodern)
(defpackage :main
  (:use cl)
  (:export :main)
  (:export :registeraction)
  )
(in-package :main)
(defparameter *actions* '())
(defun registeraction(key fn) 
  (setq *actions* (append *actions* (list (intern key) fn)))  
  )
(defun main ()
  (load "app.lisp")
  (funcall (find-symbol (string '#:register) (find-package :app)) 'registeraction)
  (woo:run
    (lambda (env)
      (funcall (getf *actions* (intern (getf env :path-info))))
      )
    :port (parse-integer (asdf::getenv "PORT"))
    :address "0.0.0.0"                      
    )
  )
